// Generated by dzn code from /home/karol/dev_projects/VerumESP32/DezyneAlarm/src/alarm-interfaces.dzn
// Dezyne --- Dezyne command line tools
// Copyright © 2024Karol Kobiela <karol.kobiela@verum.com>
//
// This file is part of Dezyne.
//
// Dezyne is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// Dezyne is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with Dezyne.  If not, see <http://www.gnu.org/licenses/>.
//
// Commentary:
//
// These models represent the actors of the alarm component.
//
// Code:
#include <dzn/runtime.hh>
namespace dzn
{
  struct locator;
  struct runtime;
}
#include <iostream>
#include <vector>
#include <map>
#ifndef ICONSOLE_HH
#define ICONSOLE_HH
struct iconsole
{
  enum struct State
    {
      Disarmed,Arming,Armed,Triggered
    };
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<bool (int pin)> arm;
    } in;
  struct
    {
      dzn::out::event<void ()> armed;
      dzn::out::event<void ()> disarmed;
      dzn::out::event<void ()> arming;
      dzn::out::event<void ()> detected;
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  ::iconsole::State state;
  iconsole (dzn::port::meta const& m);
  template <typename Component>
  iconsole (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
  , state (::iconsole::State::Disarmed)
    {
      in.arm.set (that, this, "arm");
      out.armed.set (that, this, "armed");
      out.disarmed.set (that, this, "disarmed");
      out.arming.set (that, this, "arming");
      out.detected.set (that, this, "detected");
    }
  virtual ~iconsole ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::iconsole& provide, ::iconsole& require)
    {
      provide.out.armed = require.out.armed;
      provide.out.disarmed = require.out.disarmed;
      provide.out.arming = require.out.arming;
      provide.out.detected = require.out.detected;
      require.in.arm = provide.in.arm;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // ICONSOLE_HH
#ifndef IPIN_HH
#define IPIN_HH
struct ipin
{
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<bool (int pin)> valid;
    } in;
  struct
    {
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  ipin (dzn::port::meta const& m);
  template <typename Component>
  ipin (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
    {
      in.valid.set (that, this, "valid");
    }
  virtual ~ipin ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::ipin& provide, ::ipin& require)
    {
      require.in.valid = provide.in.valid;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // IPIN_HH
#ifndef ISENSOR_HH
#define ISENSOR_HH
struct isensor
{
  dzn::port::meta dzn_meta;
  struct
    {
    } in;
  struct
    {
      dzn::out::event<void ()> MovementDetected;
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  isensor (dzn::port::meta const& m);
  template <typename Component>
  isensor (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
    {
      out.MovementDetected.set (that, this, "MovementDetected");
    }
  virtual ~isensor ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::isensor& provide, ::isensor& require)
    {
      provide.out.MovementDetected = require.out.MovementDetected;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // ISENSOR_HH
#ifndef ISIREN_HH
#define ISIREN_HH
struct isiren
{
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<void ()> disable;
      dzn::in::event<void ()> enable;
    } in;
  struct
    {
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  bool enabled;
  isiren (dzn::port::meta const& m);
  template <typename Component>
  isiren (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
  , enabled (false)
    {
      in.disable.set (that, this, "disable");
      in.enable.set (that, this, "enable");
    }
  virtual ~isiren ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::isiren& provide, ::isiren& require)
    {
      require.in.disable = provide.in.disable;
      require.in.enable = provide.in.enable;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // ISIREN_HH
#ifndef ITIMER_HH
#define ITIMER_HH
struct itimer
{
  dzn::port::meta dzn_meta;
  struct
    {
      dzn::in::event<void (int delay)> set;
      dzn::in::event<void ()> cancel;
    } in;
  struct
    {
      dzn::out::event<void ()> timeout;
    } out;
  bool dzn_share_p;
  char const* dzn_label;
  int dzn_state;
  bool idle;
  itimer (dzn::port::meta const& m);
  template <typename Component>
  itimer (dzn::port::meta const& m, Component* that)
  : dzn_meta (m)
  , dzn_share_p (true)
  , dzn_label ("")
  , dzn_state ()
  , idle (true)
    {
      in.set.set (that, this, "set");
      in.cancel.set (that, this, "cancel");
      out.timeout.set (that, this, "timeout");
    }
  virtual ~itimer ();
  void dzn_event (char const* event);
  void dzn_update_state (dzn::locator const& locator);
  void dzn_check_bindings ();
};
namespace dzn
{
  inline void connect (::itimer& provide, ::itimer& require)
    {
      provide.out.timeout = require.out.timeout;
      require.in.set = provide.in.set;
      require.in.cancel = provide.in.cancel;
      provide.dzn_meta.require = require.dzn_meta.require;
      require.dzn_meta.provide = provide.dzn_meta.provide;
      provide.dzn_share_p = require.dzn_share_p = provide.dzn_share_p && require.dzn_share_p;
    }
}
#endif // ITIMER_HH
// version 2.18.0
